# Generated by Django 4.0.1 on 2022-02-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de Autor')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido de Autor')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web Site')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('estado', models.BooleanField(default=True, verbose_name='Autor Activo/Autor Inactivo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoría Activada/Categoría Desactivada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
